apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - rolearn: arn:aws:iam::234983257537:user/duc
      username: duc
      groups:
        - system:masters