apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-examples-deployment
  labels:
    app: websocket-examples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-examples
  template:
    metadata:
      labels:
        app: websocket-examples
    spec:
      containers:
      - name: websocket-examples
        image: 234983257537.dkr.ecr.ap-southeast-1.amazonaws.com/websocket_examples:bb26f096b23378e1f4f5a4c66919921277abc119
        ports:
        - containerPort: 8084
